# Site settings
title: 
header-img: img/home-bg.png
email: mehwisha@msn.com
copyright_name: Mehwisha
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Mehwisha
learn_profile: Mehwisha
email_username: mehwisha@msn.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
